---
- name: Use fetch module to retrieve secure log files
  hosts: server1
  tasks:
    - name: Fetch the /var/log/secure log files from managed hosts
      fetch:
        src: /var/log/secure
        dest: ~/secure-backup
        flat: no
