---
- name: Configure System
  hosts: server1
  vars:
    - system_owner: parp
  tasks:
    - name: configure /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

    - name: check for file existence
      stat:
        path: /etc/motd
      register: motd

    - name: Display stat results
      debug:
        var: motd
